// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: helloworld/types/types.proto

/*
Package types is a generated protocol buffer package.

It is generated from these files:
	helloworld/types/types.proto

It has these top-level messages:
	MapEntry
	HelloRequest
	HelloResponse
*/
package types

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type MapEntry struct {
	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *MapEntry) Reset()                    { *m = MapEntry{} }
func (m *MapEntry) String() string            { return proto.CompactTextString(m) }
func (*MapEntry) ProtoMessage()               {}
func (*MapEntry) Descriptor() ([]byte, []int) { return fileDescriptorTypes, []int{0} }

func (m *MapEntry) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *MapEntry) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type HelloRequest struct {
	In string `protobuf:"bytes,1,opt,name=in,proto3" json:"in,omitempty"`
}

func (m *HelloRequest) Reset()                    { *m = HelloRequest{} }
func (m *HelloRequest) String() string            { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()               {}
func (*HelloRequest) Descriptor() ([]byte, []int) { return fileDescriptorTypes, []int{1} }

func (m *HelloRequest) GetIn() string {
	if m != nil {
		return m.In
	}
	return ""
}

type HelloResponse struct {
	Out string `protobuf:"bytes,1,opt,name=out,proto3" json:"out,omitempty"`
}

func (m *HelloResponse) Reset()                    { *m = HelloResponse{} }
func (m *HelloResponse) String() string            { return proto.CompactTextString(m) }
func (*HelloResponse) ProtoMessage()               {}
func (*HelloResponse) Descriptor() ([]byte, []int) { return fileDescriptorTypes, []int{2} }

func (m *HelloResponse) GetOut() string {
	if m != nil {
		return m.Out
	}
	return ""
}

func init() {
	proto.RegisterType((*MapEntry)(nil), "MapEntry")
	proto.RegisterType((*HelloRequest)(nil), "HelloRequest")
	proto.RegisterType((*HelloResponse)(nil), "HelloResponse")
}

func init() { proto.RegisterFile("helloworld/types/types.proto", fileDescriptorTypes) }

var fileDescriptorTypes = []byte{
	// 144 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0xc9, 0x48, 0xcd, 0xc9,
	0xc9, 0x2f, 0xcf, 0x2f, 0xca, 0x49, 0xd1, 0x2f, 0xa9, 0x2c, 0x48, 0x2d, 0x86, 0x90, 0x7a, 0x05,
	0x45, 0xf9, 0x25, 0xf9, 0x4a, 0x46, 0x5c, 0x1c, 0xbe, 0x89, 0x05, 0xae, 0x79, 0x25, 0x45, 0x95,
	0x42, 0x02, 0x5c, 0xcc, 0xd9, 0xa9, 0x95, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x20, 0xa6,
	0x90, 0x08, 0x17, 0x6b, 0x59, 0x62, 0x4e, 0x69, 0xaa, 0x04, 0x13, 0x58, 0x0c, 0xc2, 0x51, 0x92,
	0xe3, 0xe2, 0xf1, 0x00, 0x99, 0x19, 0x94, 0x5a, 0x58, 0x9a, 0x5a, 0x5c, 0x22, 0xc4, 0xc7, 0xc5,
	0x94, 0x99, 0x07, 0xd5, 0xc6, 0x94, 0x99, 0xa7, 0xa4, 0xc8, 0xc5, 0x0b, 0x95, 0x2f, 0x2e, 0xc8,
	0xcf, 0x2b, 0x4e, 0x05, 0x19, 0x9c, 0x5f, 0x5a, 0x02, 0x33, 0x38, 0xbf, 0xb4, 0x24, 0x89, 0x0d,
	0x6c, 0xbb, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xcd, 0x66, 0x97, 0xb4, 0x9d, 0x00, 0x00, 0x00,
}
